version: "3.8"

services:
  postgres:
    image: ${DOCKER_REGISTRY:?}/rocket-analytics/postgres
    build:
      context: .
      dockerfile: ./backend/postgres/Dockerfile
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME:?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      POSTGRES_DB: ${POSTGRES_DATABASE:?}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
