services:
  api:
    image: ${DOCKER_REGISTRY:?}/rocket-analytics/api
    build:
      context: .
      dockerfile: ./backend/api/Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      APP_ENV: prod
      AWS_REGION: ${AWS_REGION:?}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE:?}
      POSTGRES_DOMAIN: postgres
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    image: ${DOCKER_REGISTRY:?}/rocket-analytics/nginx
    build:
      context: .
      dockerfile: ./backend/nginx/Dockerfile
    restart: always
    ports:
      - "80:80"

  postgres:
    volumes:
      - /data:/var/lib/postgresql/data/
