version: "3.8"

services:
  postgres:
    image: ${DOCKER_REGISTRY:?}/rocket-analytics/postgres
    build:
      context: .
      dockerfile: ./backend/postgres/Dockerfile
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${PSQL_USER:?}
      POSTGRES_PASSWORD: ${PSQL_PWD:?}
      POSTGRES_DB: ${PSQL_DB:?}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PSQL_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
