version: "3.8"

services:
  postgres:
    image: ${DOCKER_REGISTRY:?}/rocket-analytics/postgres
    build:
      context: .
      dockerfile: ./backend/postgres/Dockerfile
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_username
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: ${POSTGRES_DATABASE:?}
    secrets:
      - postgres_username
      - postgres_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

secrets:
  postgres_username:
    file: postgres_username.txt
  postgres_password:
    file: postgres_password.txt
