Parameters:
  AmiId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: ServerAmiId

  AvailabilityZone:
    Type: AWS::SSM::Parameter::Value<String>
    Default: ServiceAvailabilityZone

  DatabaseVolumeId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: DatabaseVolumeId

  InstanceType:
    Type: AWS::SSM::Parameter::Value<String>
    Default: ServerInstanceType

  Region:
    Type: AWS::SSM::Parameter::Value<String>
    Default: ServiceRegion

  SecurityGroup:
    Type: AWS::SSM::Parameter::Value<String>
    Default: ServerSecurityGroup

Resources:
  Server:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Ref AvailabilityZone
      IamInstanceProfile: !Sub "ServerInstanceProfile-${Region}"
      ImageId: !Ref AmiId
      InstanceType: !Ref InstanceType
      KeyName: RocketAnalyticsSsh
      SecurityGroupIds:
        - !Ref SecurityGroup
      Volumes:
        - Device: /dev/sdf
          VolumeId: !Ref DatabaseVolumeId
