Parameters:
  WebServerInstanceType:
    Description: Select web server instance type (Not all types are available in all regions)
    Type: String
    Default: t3.small
    AllowedValues:
      - t3.nano
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large

Resources:
  WebServerIpAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: "{{resolve:ssm:WebServerIpAddressId}}"
      InstanceId: !Ref WebServer

  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: "{{resolve:ssm:AvailabilityZone}}"
      IamInstanceProfile: !Sub "WebServerInstanceProfile-${AWS::Region}"
      ImageId: "{{resolve:ssm:WebServerAmiId}}"
      InstanceType: !Ref WebServerInstanceType
      KeyName: RocketAnalyticsSsh
      SecurityGroupIds:
        - "{{resolve:ssm:WebServerSecurityGroupId}}"
      Volumes:
        - Device: /dev/sdf
          VolumeId: "{{resolve:ssm:DatabaseVolumeId}}"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash

          create_setup_script () {
            # Clone git repository to get 'rc.local.template' file
            git_repository=$(get_ssm_parameter "GitRepository")
            git_branch=$(get_ssm_parameter "GitBranch")
            git clone $git_repository /tmp/rocket-analytics
            git -C /tmp/rocket-analytics checkout $git_branch

            # Create 'rc.local' from the template file
            template=/tmp/rocket-analytics/cloudformation/rc.local.template
            cp $template /etc/rc.local && chmod 700 /etc/rc.local
          }

          # $1: Parameter name
          get_ssm_parameter () {
            echo $(aws ssm get-parameter --name $1 --region ${AWS::Region} \
              --query 'Parameter.Value' --output text)
          }

          # Update software packages (requires reboot)
          DEBIAN_FRONTEND=noninteractive apt-get -y update
          DEBIAN_FRONTEND=noninteractive apt-get -y dist-upgrade
          DEBIAN_FRONTEND=noninteractive apt-get -y install awscli git

          create_setup_script
          reboot
