Parameters:
  AmiId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: ServerAmiId

  AvailabilityZone:
    Type: AWS::SSM::Parameter::Value<String>
    Default: ServiceAvailabilityZone

  DatabaseVolumeId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: DatabaseVolumeId

  GitRepository:
    Type: AWS::SSM::Parameter::Value<String>
    Default: GitRepository

  GitBranch:
    Type: AWS::SSM::Parameter::Value<String>
    Default: GitBranch

  InstanceType:
    Type: AWS::SSM::Parameter::Value<String>
    Default: ServerInstanceType

  Region:
    Type: AWS::SSM::Parameter::Value<String>
    Default: ServiceRegion

  SecurityGroupId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: ServerSecurityGroupId

Resources:
  Server:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Ref AvailabilityZone
      IamInstanceProfile: !Sub "ServerInstanceProfile-${Region}"
      ImageId: !Ref AmiId
      InstanceType: !Ref InstanceType
      KeyName: RocketAnalyticsSsh
      SecurityGroupIds:
        - !Ref SecurityGroupId
      Volumes:
        - Device: /dev/sdf
          VolumeId: !Ref DatabaseVolumeId
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash

          create_auto_install_script () {
            # Clone git repository to get 'rc.local.template' file
            git clone ${GitRepository} /tmp/rocket-analytics
            git -C /tmp/rocket-analytics checkout ${GitBranch}

            # Create 'rc.local' from the template file
            template=/tmp/rocket-analytics/cloudformation/rc.local.template
            cp $template /etc/rc.local && chmod 700 /etc/rc.local

            # Substitute variable placeholders with actual values
            sed -i 's,\*AccountId\*,${AWS::AccountId},g' /etc/rc.local
            sed -i 's,\*DatabaseVolumeId\*,${DatabaseVolumeId},g' /etc/rc.local
            sed -i 's,\*GitRepository\*,${GitRepository},g' /etc/rc.local
            sed -i 's,\*GitBranch\*,${GitBranch},g' /etc/rc.local
            sed -i 's,\*Region\*,${Region},g' /etc/rc.local
          }

          # Update software packages (requires reboot)
          DEBIAN_FRONTEND=noninteractive apt-get -y update
          DEBIAN_FRONTEND=noninteractive apt-get -y dist-upgrade
          DEBIAN_FRONTEND=noninteractive apt-get -y install git

          create_auto_install_script
          reboot
