Parameters:
  Region:
    Description: Select region where service will be hosted
    Type: String
    Default: eu-north-1
    AllowedValues:
      # US
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      # Asia
      - ap-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      # Canada
      - ca-central-1
      # Europe
      - eu-central-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-north-1
      # South America
      - sa-east-1

  InstanceType:
    Description: Select server instance type (Not all types are available in all regions)
    Type: String
    Default: t3.micro
    AllowedValues:
      - t3.nano
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large

  AmiId:
    Description: Enter AMI ID (Use Ubuntu Server 22.04 LTS)
    Type: String

  PostgresUsername:
    Description: Username for the PostgreSQL database
    Type: String
    Default: postgres

  PostgresPassword:
    Description: Password for the PostgreSQL user
    Type: String

  PostgresDatabase:
    Description: Name for the PostgreSQL database
    Type: String
    Default: rockets

  SshIpAddress:
    Description: Enter IPv4 address which can access server over SSH
    Type: String

Conditions:
  HasSshIpAddress: !Not [!Equals [!Ref SshIpAddress, ""]]

Resources:
  # IAM Policies
  EcrPullPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      # AWS documentation states the following:
      # "Naming an IAM resource can cause an unrecoverable error if you reuse
      # the same template in multiple Regions."
      # They recommend adding region into the IAM resource name dynamically to
      # avoid this potentially unrecoverable error.
      ManagedPolicyName: !Sub "EcrPull-${Region}"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: GetAuthorizationToken
            Effect: Allow
            Action: ecr:GetAuthorizationToken
            Resource: "*"

          - Sid: PullImagesFromRepositories
            Effect: Allow
            Action:
              - ecr:BatchGetImage
              - ecr:GetDownloadUrlForLayer
            Resource:
              - !GetAtt EcrRepositoryApi.Arn
              - !GetAtt EcrRepositoryNginx.Arn
              - !GetAtt EcrRepositoryPostgres.Arn

  SsmReadParameterPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "SsmReadParameter-${Region}"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          Sid: ReadSsmParameter
          Effect: Allow
          Action: ssm:GetParameter
          Resource: "*"

  # IAM Roles
  WebServerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "WebServer-${Region}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - !Ref EcrPullPolicy
        - !Ref SsmReadParameterPolicy

  # Web server instance profile
  ServerInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub "ServerInstanceProfile-${Region}"
      Roles:
        - Ref: WebServerRole

  # SSM Parameter Store parameters
  AmiIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      DataType: text
      Description: EC2 server instance AMI ID
      Name: ServerAmiId
      Tier: Standard
      Type: String
      Value: !Ref AmiId

  InstanceTypeParameter:
    Type: AWS::SSM::Parameter
    Properties:
      DataType: text
      Description: EC2 server instance type
      Name: ServerInstanceType
      Tier: Standard
      Type: String
      Value: !Ref InstanceType

  SecurityGroupParameter:
    Type: AWS::SSM::Parameter
    Properties:
      DataType: text
      Description: Security group ID for the web server
      Name: ServerSecurityGroup
      Tier: Standard
      Type: String
      Value: !GetAtt WebServerSecurityGroup.GroupId

  ServiceRegionParameter:
    Type: AWS::SSM::Parameter
    Properties:
      DataType: text
      Description: AWS region for the web service
      Name: ServiceRegion
      Tier: Standard
      Type: String
      Value: !Ref Region

  AvailabilityZoneParameter:
    Type: AWS::SSM::Parameter
    Properties:
      DataType: text
      Description: Availability zone for the web service
      Name: ServiceAvailabilityZone
      Tier: Standard
      Type: String
      Value: !Select [0, Fn::GetAZs: !Ref Region]

  DatabaseVolumeParameter:
    Type: AWS::SSM::Parameter
    Properties:
      DataType: text
      Description: Database EBS volume ID
      Name: DatabaseVolumeId
      Tier: Standard
      Type: String
      Value: !GetAtt DatabaseVolume.VolumeId

  PostgresUsernameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      DataType: text
      Description: Username for the PostgreSQL database
      Name: PSQL_USER
      Tier: Standard
      Type: String
      Value: !Ref PostgresUsername

  PostgresPasswordParameter:
    Type: AWS::SSM::Parameter
    Properties:
      DataType: text
      Description: Password for the PostgreSQL user
      Name: PSQL_PWD
      Tier: Standard
      Type: String
      Value: !Ref PostgresPassword

  PostgresDatabaseParameter:
    Type: AWS::SSM::Parameter
    Properties:
      DataType: text
      Description: Name for the PostgreSQL database
      Name: PSQL_DB
      Tier: Standard
      Type: String
      Value: !Ref PostgresDatabase

  DockerRegistryParameter:
    Type: AWS::SSM::Parameter
    Properties:
      DataType: text
      Description: Base URI to the Elastic Container Registry
      Name: DOCKER_REGISTRY
      Tier: Standard
      Type: String
      Value: !Sub "${AWS::AccountId}.dkr.ecr.${Region}.amazonaws.com"

  # ECR repositories
  EcrRepositoryApi:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: rocket-analytics/api

  EcrRepositoryNginx:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: rocket-analytics/nginx

  EcrRepositoryPostgres:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: rocket-analytics/postgres

  # Database volume
  DatabaseVolume:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: !GetAtt AvailabilityZoneParameter.Value
      Size: 8
      VolumeType: gp3

  # Security group
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: WebServer
      GroupDescription: HTTP and SSH traffic to the web server
      SecurityGroupIngress:
        - Description: Open HTTP to the NGINX
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

        # Create rule for SSH if IP address parameter is provided
        - !If
          - HasSshIpAddress
          - Description: Open SSH to the EC2
            IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: !Sub "${SshIpAddress}/32"
          - !Ref AWS::NoValue
