"""Adds foreign key from Flight to User

Revision ID: b4807997474b
Revises: c33ee9630a91
Create Date: 2023-11-25 20:26:17.381427+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4807997474b'
down_revision: Union[str, None] = 'c33ee9630a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'flights', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flights', type_='foreignkey')
    op.drop_column('flights', 'user_id')
    # ### end Alembic commands ###
